spring:
  datasource:
    url: jdbc:mysql://112.74.185.228:3306/blog
    username: blog
    password: KGdn2X4jtmdLb4dd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.corey: debug
  file:
    name: log/blog-dev.log